== Part 2: Introduce reactive microservices architecture

In this part, we will separate a module of the monolith into a standalone microservice, running with Payara Micro. We will then look at the ways how to extend the reactive concepts to the architecture of microservices, beyond a single monolith.


=== 1. Introduce a microservice

We want to separate the `GraphTraversalService` module into a standalone Pathfinder microservice. This will give several advantages:

* The code can evolve separately from the monolith
* We can run several instances of Pathfinder to scale (speed up) the application

**Tasks**:

* create a WAR maven project called `pathfinder`
* create a JAR maven project called `pathfinder-api` and add it as a dependency to the new WAR project and also to the existing monolith project
* move common GraphTraversalService classes to `pathfinder-api` (TransitEdge, TransitPath, GraphTraversalRequest, GraphTraversalResponse)
* move all other GraphTraversalService to `pathfinder` (GraphTraversalService, GraphDao)

Because the communication already goes through the CDI event bus, we don't need to let the monolith know how to route the events. We just need to make sure that Pathfinder joins the same cloud as the monolith.

=== 2. Run the microservice architecture

Start with the branch `11_jee8_separate_microservice` in both repositories.

There are 2 new maven modules:

 - Pathfinder service (WAR) - a separate microservice providing GraphTraversalService service as both a REST resource and via Payara CDI event bus
 - Pathfinder API (JAR) - common code reused in both the monolithic application and the Pathfinder micro service

**Tasks:**

 1. run `mvn clean install` in the root of this repository (for the top-level maven module)
 2. deploy the monolithic cargo-tracker application to Payara Server as before
 3. run Pathfinder micro service with Payara Micro - go to the directory `pathfinder/target` and execute: `java -jar payara-micro.jar -clustermode domain -autobindhttp pathfinder.war` (alternatively use the https://docs.payara.fish/documentation/ecosystem/maven-plugin.html[Payara Micro maven plugin])

The `-autobindhttp` argument to Payara Micro instructs the service to bind the HTTP listener to an available port. Since the monolithic application already occupies the port 8080, therefore the Pathfinder service will probably bind to the port 8081. We can find out the port from the console output. We can check that the application is running with the following URL: http://localhost:8081/pathfinder/rest/graph-traversal/shortest-path?origin=CNHKG&destination=AUMEL

The port number is not important and can even vary. The monolith communicates with the service using the CDI even bus messages and doesn't use the REST endpoint. 

=== 3. Introduce JCache for caching and process synchronization


JCache can be used for caching of results to optimize repetitive processing. But if the cache is distributed, it also provides distributed locks, which we will use to synchronize message observers so that at most one of them processes the message.

**Tasks:**

* add JCache maven dependency to both projects: `javax.cache:cache-api:1.1.0`
* Inject `javax.cache.Cache<Long, String>` into `GraphTraversalResource`, give it a name with `@NamedCache`
* 

The branch `12_jee8_load_balancing_01_jcache` contains complete solution. 


=== Run the microservices

Deploy and run the main application in a usual way on Payara Server.

Run the Pathfinder microservice with Payara Micro:

`java -jar target/payara-micro.jar -deploy target/pathfinder.war -autobindhttp`

Try if the route cargo page is working, check the logs of the main application and the Pathfinder service.

Run a second instance of the Pathfinder microservice, now using the standalone JAR built by Payara maven plugin:

`java -jar pathfinder-uber.jar`

Request the route cargo page and watch the log files of both pathfinder services. On of them will log "Received a computation request", which means it will compute and provide the results. Another one will log "Ignoring computation request", which means it detected a computation started in the first instance and ignores the request. 

If you load the page several times, you'll see that the computation is balanced and switches randomly between the 2 instances.

If you stop any of the pathfinder services and load the route cargo page again you'll see that the application still works. The computation is performed on the running pathfinder service. You can start another pathfinder service and stop the former and the page will still load without any problem.